# Generated by Django 5.1.4 on 2025-04-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_student_logical_score_student_numerical1_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '10-12'), ('ug', 'pg')], max_length=20),
        ),
    ]
