# Generated by Django 5.1.4 on 2025-04-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9'), ('10-12', '10-12'), ('ug', 'ug'), ('pg', 'pg')], max_length=20),
        ),
    ]
